# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('NUTRITION', 'Nutritionist'), ('TRAIN', 'Personal Trainer'), ('MD', 'Doctor'), ('User', 'User')], default='User', max_length=15),
        ),
    ]
