# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170226_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
