# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(related_name='_user_group_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
