# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='media/noprofile.png', upload_to='media/'),
        ),
    ]
