# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
