# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170316_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.TextField(default='', max_length=100),
        ),
    ]
