# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doer', to=settings.AUTH_USER_MODEL)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
